version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: classroom
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build:
      context: .              # Thư mục chứa Dockerfile
      dockerfile: Dockerfile
    container_name: classroom_backend
    depends_on:
      - mysql
    ports:
      - "8888:8888"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_DB: classroom
    restart: always

volumes:
  mysql_data:
