// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	"backend/service/classroom/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// ForgetPassword
				Method:  http.MethodPost,
				Path:    "/user/forget-password",
				Handler: ForgetPasswordHandler(serverCtx),
			},
			{
				// Login
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				// Register
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				// VerifyEmailNoAuth
				Method:  http.MethodGet,
				Path:    "/verify-email",
				Handler: VerifyEmailNoAuthHandler(serverCtx),
			},
		},
		rest.WithPrefix("/classroom"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// AddClass
				Method:  http.MethodPost,
				Path:    "/class",
				Handler: AddClassHandler(serverCtx),
			},
			{
				// GetUsers
				Method:  http.MethodGet,
				Path:    "/user",
				Handler: GetUsersHandler(serverCtx),
			},
			{
				// GetUser
				Method:  http.MethodGet,
				Path:    "/user/:user_id",
				Handler: GetUserHandler(serverCtx),
			},
			{
				// UpdateUser
				Method:  http.MethodPut,
				Path:    "/user/:user_id",
				Handler: UpdateUserHandler(serverCtx),
			},
			{
				// DeleteUser
				Method:  http.MethodDelete,
				Path:    "/user/:user_id",
				Handler: DeleteUserHandler(serverCtx),
			},
			{
				// ResetPassword
				Method:  http.MethodPost,
				Path:    "/user/reset-password",
				Handler: ResetPasswordHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/classroom"),
	)
}
