// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type AddClassData struct {
	Class   Class   `json:"class"`
	Teacher Teacher `json:"teacher:`
}

type AddClassReq struct {
	ClassName   string `json:"class_name"`
	Description string `json:"description"`
}

type AddClassRes struct {
	Code    int          `json:"code"`
	Message string       `json:"message"`
	Data    AddClassData `json:"data"`
}

type Class struct {
	Id          int64  `json:"id"`
	ClassCode   string `json:"class_code"`
	ClassName   string `json:"class_name"`
	Description string `json:"description"`
	TeacherId   int64  `json:"teacher_id"`
	CreateTime  int64  `json:"create_time"`
	UpdateTime  int64  `json:"update_time"`
}

type DeleteUserReq struct {
	UserId int64 `path:"user_id"`
}

type DeleteUserRes struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type EmailConfirmation struct {
	Id               int64  `json:"id"`
	UserId           int64  `json:"user_id"`
	ConfirmationCode string `json:"confirmation_code"`
	IsVerified       bool   `json:"is_verified"`
	SentTime         string `json:"sent_time"`
	VerifiedTime     string `json:"verified_time"`
}

type Enrollment struct {
	Id        int64  `json:"id"`
	StudentId int64  `json:"student_id"`
	ClassId   int64  `json:"class_id"`
	JoinTime  string `json:"join_time"`
}

type ForgetPasswordReq struct {
	UserName string `json:"user_name"`
	Email    string `json:"email"`
}

type ForgetPasswordRes struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type GetUserData struct {
	User User `json:"user"`
}

type GetUserReq struct {
	UserId int64 `path:"user_id"`
}

type GetUserRes struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Data    GetUserData `json:"data"`
}

type GetUsersData struct {
	User []User `json:"user"`
}

type GetUsersReq struct {
	Email  string `form:"email,optional"`
	Limit  int    `form:"limit"`  // == 0 get all
	Offset int    `form:"offset"` // offset of page
}

type GetUsersRes struct {
	Code    int          `json:"code"`    // Result code: 0 is success. Otherwise, getting an error
	Message string       `json:"message"` // Result message: detail response code
	Data    GetUsersData `json:"data"`
}

type Grade struct {
	Id          int64   `json:"id"`
	StudentId   int64   `json:"student_id"`
	ComponentId int64   `json:"component_id"`
	Score       float64 `json:"score"`
	GradeTime   string  `json:"grade_time"`
}

type GradeComponent struct {
	Id            int64   `json:"id"`
	SubjectId     int64   `json:"subject_id"`
	ComponentName string  `json:"component_name"`
	Weight        float64 `json:"weight"`
}

type Lesson struct {
	Id         int64  `json:"id"`
	SubjectId  int64  `json:"subject_id"`
	Title      string `json:"title"`
	Content    string `json:"content"`
	FileUrl    string `json:"file_url"`
	UploadTime int64  `json:"upload_time"`
}

type LoginData struct {
	User  User   `json:"user"`
	Token string `json:"token"`
}

type LoginReq struct {
	UserName string `json:"user_name"`
	PassWord string `json:"password"`
}

type LoginRes struct {
	Code    int       `json:"code"`
	Message string    `json:"message"`
	Data    LoginData `json:"data"`
}

type RegisterData struct {
	User  User   `json:"user"`  // Account info
	Token string `json:"token"` // jwt token for api
}

type RegisterReq struct {
	UserName    string `json:"user_name"`
	Password    string `json:"password"`
	Email       string `json:"email"`
	PhoneNumber string `json:"phone_number"`
	FullName    string `json:"full_name"`
	Gender      int    `json:"gender"`
}

type RegisterRes struct {
	Code    int          `json:"code"`    // Result code: 0 is success. Otherwise, getting an error
	Message string       `json:"message"` // Result message: detail response code
	Data    RegisterData `json:"data"`
}

type ResetPasswordReq struct {
	Username string `json:"user_name"`
	PassWord string `json:"password"`
}

type ResetPasswordRes struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

type Subject struct {
	Id          int64  `json:"id"`
	ClassId     int64  `json:"class_id"`
	SubjectName string `json:"subject_name"`
	Description string `json:"description"`
	CreateTime  int64  `json:"create_time"`
	UpdateTime  int64  `json:"update_time"`
}

type Teacher struct {
	TeacherId  int64  `json:"teacher_id"`
	ClassId    int64  `json:"class_id"`
	UserId     int64  `json:"user_id"`
	Bio        string `json:"bio"`
	CreateTime int64  `json:"create_time"`
	UpdateTime int64  `json:"update_time"`
}

type UpdateUserData struct {
	User User `json:"user"`
}

type UpdateUserReq struct {
	UserId      int64  `path:"user_id"`
	PhoneNumber string `form:"phone_number"`
	Gender      int    `form:"gender"`
	FullName    string `form:"full_name"`
}

type UpdateUserRes struct {
	Code    int            `json:"code"`    // Result code: 0 is success. Otherwise, getting an error
	Message string         `json:"message"` // Result message: detail response code
	Data    UpdateUserData `json:"data"`
}

type User struct {
	Id               int64  `json:"id"`
	UserName         string `json:"user_name"`
	Password         string `json:"password"`
	Email            string `json:"email"`
	PhoneNumber      string `json:"phone_number"`
	Gender           int    `json:"gender"` // 0: unknown, 1: male, 2: female
	FullName         string `json:"full_name"`
	Avatar           string `json:"avatar"`
	IsVerified       bool   `json:"is_verified"`
	VerificationCode string `json:"verification_code"`
	Role             int    `json:"role"` // 1: teacher, 2: student
	CreateTime       int64  `json:"create_time"`
	UpdateTime       int64  `json:"update_time"`
}

type VerifyEmailNoAuthReq struct {
	Email string `form:"email"`
	Token string `form:"token"`
}

type VerifyEmailNoAuthRes struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}
